[CALCITE-5701] Add NAMED_STRUCT function (enabled in Spark library)
apache/calcite pull request #3295
Opened 2023-07-05 02:17 UTC by MasseGuillaume

2023-07-05 02:21 UTC, MasseGuillaume commented on core/src/main/java/org/apache/calcite/interpreter/NamedStruct.java
> +public class NamedStruct extends StructImpl {
It was necessary to subclass `StructImpl` in order to pass the Quidem tests

https://github.com/apache/calcite-avatica/blob/be8b99aeede2883e5692124edd187eaeffabed2c/core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java#L1479

2023-07-05 05:47 UTC, NobiGo requested changes
Some comments need to change.

2023-07-05 05:47 UTC, NobiGo commented on core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableInterpretable.java
> -          + s, e);
This is unrelated changes about this ISSUE, If you think this message needs to improve, Please log a new issue in Jira.

2023-07-05 05:47 UTC, NobiGo commented on core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
> +
Unrelated changes, Please remove them.

2023-07-05 05:47 UTC, NobiGo commented on core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
> +
In order to keep the code style unified, Please remove empty lines.

2023-07-05 06:16 UTC, MasseGuillaume commented
For some reason, GitHub is not showing all the commit range: https://github.com/MasseGuillaume/calcite/commits/CALCITE-5701-2

2023-07-06 12:11 UTC, ILuffZhe commented
Hi @MasseGuillaume . I noticed that your PR contains someone else codes(maybe it's due to the force push), can you adjust your patch？ So we can proceed to the next step.

2023-07-17 07:02 UTC, gabrywu commented
any update here?

2023-07-17 14:00 UTC, MasseGuillaume commented
@gabrywu 

I'm stuck on the runtime implementation.

in JIRA: https://issues.apache.org/jira/browse/CALCITE-5701?focusedCommentId=17741811&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17741811
> You should not be using SqlFunctions.item. The javadoc says "Implements item on an object whose type is not known until runtime". But you know the type is STRUCT(k1 VARCHAR, K2 INTEGER). You know that "k1" is item zero of the Object[]. You should translate "item" call to a field access. And then none of your changes to ItemImplementor will be necessary.

I'm not too sure where that `translate "item" call to a field access` should happen. Maybe during the validation. (eg. `performUnconditionalRewrites`).

2024-07-09 15:57 UTC, closed without merging