[CALCITE-5922] POSITION signature incorrect for SparkSQL
apache/calcite pull request #3363
Opened 2023-08-13 08:31 UTC by macroguo-ghy

2023-08-14 02:25 UTC, JiajunBernoulli approved these changes

2023-08-17 03:34 UTC, macroguo-ghy commented
Hi @JiajunBernoulli , I have made a change to the git comment and JIRA summary without any other modifications. Would you like to review it again and then merge this PR?

2023-08-18 01:37 UTC, NobiGo requested changes

2023-08-18 01:37 UTC, NobiGo commented on core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
> +      case POSITION:
I noticed `POSITION('a', 'abc')` and `POSITION('a' IN 'abc')` all works in Spark. So we can use 
` case POSITION:
    SqlUtil.unparseFunctionSyntax(SqlStdOperatorTable.POSITION, writer, call, false);`. WDYT?

2023-08-18 11:05 UTC, NobiGo approved these changes
LGTM

2023-08-24 02:01 UTC, JiajunBernoulli commented
@macroguo-ghy  Please squash commits, I will merge it tomorrow.

2023-08-24 02:41 UTC, macroguo-ghy commented
@JiajunBernoulli  Done.

2023-08-25 11:07 UTC, merged